# Generated by Django 3.0.3 on 2020-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='may',
            options={'ordering': ['-published'], 'verbose_name': 'Могу', 'verbose_name_plural': 'Могу'},
        ),
        migrations.AlterModelOptions(
            name='must',
            options={'ordering': ['-published'], 'verbose_name': 'Надо', 'verbose_name_plural': 'Надо'},
        ),
        migrations.AlterModelOptions(
            name='want',
            options={'ordering': ['-published'], 'verbose_name': 'Хочу', 'verbose_name_plural': 'Хочу'},
        ),
        migrations.RemoveField(
            model_name='may',
            name='content',
        ),
        migrations.RemoveField(
            model_name='must',
            name='content',
        ),
        migrations.RemoveField(
            model_name='want',
            name='content',
        ),
        migrations.AddField(
            model_name='must',
            name='edited',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='may',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='must',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='want',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Запись'),
        ),
    ]
